version: "3.8"

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./public:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
  php:
    build: ./docker/php-fpm
    volumes:
      - ./public:/var/www/html
    depends_on:
      - db
  db:
    build: ./docker/mysql
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: security
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: secret
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8888:80
    depends_on:
      - db
volumes:
  db-data:
